# Generated by Django 2.0.1 on 2018-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='asin',
            field=models.CharField(default='DEFAULT_ASIN', max_length=200),
            preserve_default=False,
        ),
    ]
