# Generated by Django 2.0.1 on 2018-02-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='negative_reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='positive_reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
